package net.sf.okapi.steps.common.stepintrospector;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.FIELD)
public @interface StepExternalParameter {
	/**
	 * External parameters can be classified according to usage. Some are input
	 * only. Some are output only. In rare cases a parameter can be both input
	 * and output.
	 */
	StepParameterAccessType accessType() default StepParameterAccessType.READ_ONLY;

	/**
	 * If this parameter is generated by a pipeline step rather than by a
	 * external client then list the required step here.
	 */
	String requiredStep() default "";

	/**
	 * Short UI displayable description of the parameter.
	 */
	String description();

	/**
	 * Long UI displayable description of the parameter.
	 */
	String longDescription();
}
