/* Generated By:JavaCC: Do not edit this line. WordTokenizerConstants.java */
package net.sf.okapi.lib.search.lucene.analysis;

public interface WordTokenizerConstants {

  int EOF = 0;
  int HYPHENATED = 1;
  int ALPHANUM = 2;
  int APOSTROPHE = 3;
  int ACRONYM = 4;
  int COMPANY = 5;
  int EMAIL = 6;
  int HOST = 7;
  int NUM = 8;
  int P = 9;
  int HAS_DIGIT = 10;
  int ALPHA = 11;
  int LETTER = 12;
  int DIGIT = 13;
  int NOISE = 14;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<HYPHENATED>",
    "<ALPHANUM>",
    "<APOSTROPHE>",
    "<ACRONYM>",
    "<COMPANY>",
    "<EMAIL>",
    "<HOST>",
    "<NUM>",
    "<P>",
    "<HAS_DIGIT>",
    "<ALPHA>",
    "<LETTER>",
    "<DIGIT>",
    "<NOISE>",
  };

}
