
package com.crosslang.ws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "Gateway", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://77.241.87.220/Gateway.svc?wsdl")
public class Gateway
    extends Service
{

    private final static URL GATEWAY_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.crosslang.ws.Gateway.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.crosslang.ws.Gateway.class.getResource(".");
            url = new URL(baseUrl, "http://77.241.87.220/Gateway.svc?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://77.241.87.220/Gateway.svc?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        GATEWAY_WSDL_LOCATION = url;
    }

    public Gateway(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Gateway() {
        super(GATEWAY_WSDL_LOCATION, new QName("http://tempuri.org/", "Gateway"));
    }

    /**
     * 
     * @return
     *     returns IGateway
     */
    @WebEndpoint(name = "DefaultBinding")
    public IGateway getDefaultBinding() {
        return super.getPort(new QName("http://tempuri.org/", "DefaultBinding"), IGateway.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IGateway
     */
    @WebEndpoint(name = "DefaultBinding")
    public IGateway getDefaultBinding(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "DefaultBinding"), IGateway.class, features);
    }

}
