
package com.crosslang.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "IGateway", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IGateway {


    /**
     * 
     * @param departmentId
     * @param user
     * @param apiKey
     * @param sourceString
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetTranslatedString", action = "http://tempuri.org/IGateway/GetTranslatedString")
    @WebResult(name = "GetTranslatedStringResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetTranslatedString", targetNamespace = "http://tempuri.org/", className = "com.crosslang.ws.GetTranslatedString")
    @ResponseWrapper(localName = "GetTranslatedStringResponse", targetNamespace = "http://tempuri.org/", className = "com.crosslang.ws.GetTranslatedStringResponse")
    public String getTranslatedString(
        @WebParam(name = "user", targetNamespace = "http://tempuri.org/")
        String user,
        @WebParam(name = "apiKey", targetNamespace = "http://tempuri.org/")
        String apiKey,
        @WebParam(name = "departmentId", targetNamespace = "http://tempuri.org/")
        String departmentId,
        @WebParam(name = "sourceString", targetNamespace = "http://tempuri.org/")
        String sourceString);

    /**
     * 
     * @param departmentId
     * @param user
     * @param apiKey
     * @param options
     * @param sourceString
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetTranslatedString_WithOptions", action = "http://tempuri.org/IGateway/GetTranslatedString_WithOptions")
    @WebResult(name = "GetTranslatedString_WithOptionsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetTranslatedString_WithOptions", targetNamespace = "http://tempuri.org/", className = "com.crosslang.ws.GetTranslatedStringWithOptions")
    @ResponseWrapper(localName = "GetTranslatedString_WithOptionsResponse", targetNamespace = "http://tempuri.org/", className = "com.crosslang.ws.GetTranslatedStringWithOptionsResponse")
    public String getTranslatedStringWithOptions(
        @WebParam(name = "user", targetNamespace = "http://tempuri.org/")
        String user,
        @WebParam(name = "apiKey", targetNamespace = "http://tempuri.org/")
        String apiKey,
        @WebParam(name = "departmentId", targetNamespace = "http://tempuri.org/")
        String departmentId,
        @WebParam(name = "sourceString", targetNamespace = "http://tempuri.org/")
        String sourceString,
        @WebParam(name = "options", targetNamespace = "http://tempuri.org/")
        ArrayOfstring options);

    /**
     * 
     * @param fileType
     * @param departmentId
     * @param utf8Base64EncodedString
     * @param user
     * @param apiKey
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetTranslatedFile", action = "http://tempuri.org/IGateway/GetTranslatedFile")
    @WebResult(name = "GetTranslatedFileResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetTranslatedFile", targetNamespace = "http://tempuri.org/", className = "com.crosslang.ws.GetTranslatedFile")
    @ResponseWrapper(localName = "GetTranslatedFileResponse", targetNamespace = "http://tempuri.org/", className = "com.crosslang.ws.GetTranslatedFileResponse")
    public String getTranslatedFile(
        @WebParam(name = "user", targetNamespace = "http://tempuri.org/")
        String user,
        @WebParam(name = "apiKey", targetNamespace = "http://tempuri.org/")
        String apiKey,
        @WebParam(name = "departmentId", targetNamespace = "http://tempuri.org/")
        String departmentId,
        @WebParam(name = "utf8_base64_EncodedString", targetNamespace = "http://tempuri.org/")
        String utf8Base64EncodedString,
        @WebParam(name = "fileType", targetNamespace = "http://tempuri.org/")
        String fileType);

    /**
     * 
     * @param fileType
     * @param departmentId
     * @param utf8Base64EncodedString
     * @param user
     * @param apiKey
     * @param options
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetTranslatedFile_WithOptions", action = "http://tempuri.org/IGateway/GetTranslatedFile_WithOptions")
    @WebResult(name = "GetTranslatedFile_WithOptionsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetTranslatedFile_WithOptions", targetNamespace = "http://tempuri.org/", className = "com.crosslang.ws.GetTranslatedFileWithOptions")
    @ResponseWrapper(localName = "GetTranslatedFile_WithOptionsResponse", targetNamespace = "http://tempuri.org/", className = "com.crosslang.ws.GetTranslatedFileWithOptionsResponse")
    public String getTranslatedFileWithOptions(
        @WebParam(name = "user", targetNamespace = "http://tempuri.org/")
        String user,
        @WebParam(name = "apiKey", targetNamespace = "http://tempuri.org/")
        String apiKey,
        @WebParam(name = "departmentId", targetNamespace = "http://tempuri.org/")
        String departmentId,
        @WebParam(name = "utf8_base64_EncodedString", targetNamespace = "http://tempuri.org/")
        String utf8Base64EncodedString,
        @WebParam(name = "fileType", targetNamespace = "http://tempuri.org/")
        String fileType,
        @WebParam(name = "options", targetNamespace = "http://tempuri.org/")
        ArrayOfstring options);

    /**
     * 
     * @param departmentId
     * @param companyId
     * @param user
     * @param apiKey
     * @return
     *     returns com.crosslang.ws.ArrayOfstring
     */
    @WebMethod(operationName = "GetSupportedLanguages", action = "http://tempuri.org/IGateway/GetSupportedLanguages")
    @WebResult(name = "GetSupportedLanguagesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetSupportedLanguages", targetNamespace = "http://tempuri.org/", className = "com.crosslang.ws.GetSupportedLanguages")
    @ResponseWrapper(localName = "GetSupportedLanguagesResponse", targetNamespace = "http://tempuri.org/", className = "com.crosslang.ws.GetSupportedLanguagesResponse")
    public ArrayOfstring getSupportedLanguages(
        @WebParam(name = "user", targetNamespace = "http://tempuri.org/")
        String user,
        @WebParam(name = "companyId", targetNamespace = "http://tempuri.org/")
        String companyId,
        @WebParam(name = "departmentId", targetNamespace = "http://tempuri.org/")
        String departmentId,
        @WebParam(name = "apiKey", targetNamespace = "http://tempuri.org/")
        String apiKey);

}
